### ISSUE TITLE
Watch monogatari

### ISSUE THREAD

**Issue by kuator** [elianiva/japanese-stuff#1]
windows inspired Monogatari  animation: https://kuator.github.io/gh-pages/image-reveal-kinda/

**Comment by elianiva** [comment]
actually, thank you for reminding me. I've been slacking off with my japanese for weeks lol

**Comment by kuator** [comment]
I also study japanese, but I decided to start with Heisig, so I'm stuck with kanjis for a while

**Comment by elianiva** [comment]
right, *that* book. I was thinking about buying that a few months ago but then I thought, meh, screw it, I'll learn them as I go -- and here I am, still stuck with N5 after a year because I procrastinate too much

**Comment by kuator** [comment]
Same for me, there is just so much resources, approaches, methods to learn a language - you end up choosing nothing and procrastinating and hating yourself. So I just went "screw it" and downloaded Heisig and decided to stick with it.
